SCRN_WD = 1280
SCRN_HT = 720

SPCROCK_MIN_RAD = 20
SPCROCK_KINDS = 3
SPCROCK_SPAWN_RATE = 0.8  # seconds
SPCROCK_MAX_RAD = SPCROCK_MIN_RAD * SPCROCK_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHT_COOLDOWN_SCNDS = 0.3

SHOT_RAD = 5
